# Generated by Django 4.1.13 on 2023-11-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_field', models.CharField(blank=True, max_length=255, null=True)),
                ('field_type', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('date', 'Date'), ('text', 'Text')], max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('field_name_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_1', to='app.formdata')),
                ('field_name_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_2', to='app.formdata')),
                ('field_name_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_3', to='app.formdata')),
                ('field_name_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_4', to='app.formdata')),
            ],
        ),
    ]
